# Attention 구하기

In [55]:
import numpy as np

T, H = 5, 4 # hs가 5 * 4

hs = np.random.randn(T, H)
a = np.array([0.8, 0.1, 0.03, 0.05, 0.02])

In [56]:
hs

array([[-0.09506591,  1.4179322 , -0.60965677, -0.12385157],
       [ 1.44014097,  1.89251067, -0.56617163, -1.04083874],
       [ 0.56333645, -0.78583158, -0.3871122 ,  1.42459785],
       [ 0.21737561, -0.07718205,  0.40015143,  0.4330996 ],
       [ 0.148657  ,  0.57659627, -1.00711315, -0.33250698]])

In [57]:
a

array([0.8 , 0.1 , 0.03, 0.05, 0.02])

In [58]:
print(a.shape)

(5,)


In [61]:
ar_t = a.reshape(5, 1)

In [62]:
ar_t

array([[0.8 ],
       [0.1 ],
       [0.03],
       [0.05],
       [0.02]])

In [66]:
ar1 = ar_t.repeat(4)
ar1

array([0.8 , 0.8 , 0.8 , 0.8 , 0.1 , 0.1 , 0.1 , 0.1 , 0.03, 0.03, 0.03,
       0.03, 0.05, 0.05, 0.05, 0.05, 0.02, 0.02, 0.02, 0.02])

In [65]:
ar2 = ar_t.repeat(4, axis=1)
ar2

array([[0.8 , 0.8 , 0.8 , 0.8 ],
       [0.1 , 0.1 , 0.1 , 0.1 ],
       [0.03, 0.03, 0.03, 0.03],
       [0.05, 0.05, 0.05, 0.05],
       [0.02, 0.02, 0.02, 0.02]])

In [67]:
ar = a.reshape(5, 1).repeat(4, axis=1)

In [68]:
ar

array([[0.8 , 0.8 , 0.8 , 0.8 ],
       [0.1 , 0.1 , 0.1 , 0.1 ],
       [0.03, 0.03, 0.03, 0.03],
       [0.05, 0.05, 0.05, 0.05],
       [0.02, 0.02, 0.02, 0.02]])

In [69]:
print(ar.shape)

(5, 4)


In [70]:
t = hs * ar

In [71]:
t

array([[-0.07605272,  1.13434576, -0.48772542, -0.09908126],
       [ 0.1440141 ,  0.18925107, -0.05661716, -0.10408387],
       [ 0.01690009, -0.02357495, -0.01161337,  0.04273794],
       [ 0.01086878, -0.0038591 ,  0.02000757,  0.02165498],
       [ 0.00297314,  0.01153193, -0.02014226, -0.00665014]])

In [72]:
print(t.shape)

(5, 4)


In [73]:
c = np.sum(t, axis=0)
print(c.shape)

(4,)


In [74]:
c

array([ 0.09870339,  1.30769471, -0.55609064, -0.14542236])

# Mini-Batch 

In [78]:
N, T, H = 10, 5, 4

hs = np.random.randn(N, T, H)
hs

array([[[-1.44308849e+00, -2.05069079e-01,  5.96293263e-02,
          8.12029254e-01],
        [-2.07630511e+00, -1.21602371e+00,  1.13300275e-01,
         -1.91930105e+00],
        [-2.07911163e-01, -1.18528444e-01, -1.99147888e+00,
          6.56277744e-01],
        [ 3.28607920e-01,  8.25626873e-01, -3.14683300e-01,
         -5.14413278e-01],
        [-9.83868290e-01, -7.69113923e-02, -1.59289285e+00,
         -2.06530783e-01]],

       [[ 1.94929234e+00,  5.72534824e-01,  1.64151255e+00,
          1.89091909e+00],
        [ 4.76252634e-01,  1.67503277e+00, -8.33611355e-03,
          6.29468485e-02],
        [ 1.63019904e-01, -2.01375097e+00, -1.26048714e+00,
         -2.08981749e+00],
        [ 1.64418771e+00,  1.28243122e+00, -9.32447571e-01,
         -1.11347852e+00],
        [-5.77059756e-01,  6.91650873e-01,  1.39247773e+00,
         -3.91817417e-01]],

       [[ 5.21958164e-01,  1.51955911e+00, -6.61051204e-01,
          7.82256704e-01],
        [-1.36689323e+00, -7.87800617e-

In [79]:
print(hs.shape)

(10, 5, 4)


In [81]:
a = np.random.randn(N, T)
a

array([[ 0.5002953 , -1.31032562,  0.78230321,  0.63880349, -0.58852368],
       [-1.5399924 , -0.52637526,  0.76043897,  0.83754503,  0.97572897],
       [-0.02177147,  2.00209365,  1.86983552,  0.06865877,  0.48804842],
       [ 0.15469091, -1.75571644, -1.4889199 ,  0.83711775, -0.12328329],
       [ 1.27422696, -0.25939711, -0.34211276, -0.83346233, -0.99014657],
       [-0.86162664, -0.29728421, -0.29046957, -0.98709418,  0.45385976],
       [-0.50091422,  0.24720591,  0.27678445, -0.01642606, -0.00668   ],
       [-0.02179219, -0.78024524, -1.41969485, -1.0026959 ,  0.5029967 ],
       [-1.30671024, -0.29737149, -0.13280915, -1.90441479,  0.00379048],
       [ 1.48459454, -1.41605363, -0.15013064, -0.25393247, -0.40092451]])

In [ ]:
a

In [82]:
print(a.shape)

(10, 5)


In [83]:
ar = a.reshape(N, T, 1)

In [84]:
ar

array([[[ 0.5002953 ],
        [-1.31032562],
        [ 0.78230321],
        [ 0.63880349],
        [-0.58852368]],

       [[-1.5399924 ],
        [-0.52637526],
        [ 0.76043897],
        [ 0.83754503],
        [ 0.97572897]],

       [[-0.02177147],
        [ 2.00209365],
        [ 1.86983552],
        [ 0.06865877],
        [ 0.48804842]],

       [[ 0.15469091],
        [-1.75571644],
        [-1.4889199 ],
        [ 0.83711775],
        [-0.12328329]],

       [[ 1.27422696],
        [-0.25939711],
        [-0.34211276],
        [-0.83346233],
        [-0.99014657]],

       [[-0.86162664],
        [-0.29728421],
        [-0.29046957],
        [-0.98709418],
        [ 0.45385976]],

       [[-0.50091422],
        [ 0.24720591],
        [ 0.27678445],
        [-0.01642606],
        [-0.00668   ]],

       [[-0.02179219],
        [-0.78024524],
        [-1.41969485],
        [-1.0026959 ],
        [ 0.5029967 ]],

       [[-1.30671024],
        [-0.29737149],
        [-0.132809

In [85]:
print(ar.shape)

(10, 5, 1)


In [86]:
ar = ar.repeat(H, 2)
ar

array([[[ 0.5002953 ,  0.5002953 ,  0.5002953 ,  0.5002953 ],
        [-1.31032562, -1.31032562, -1.31032562, -1.31032562],
        [ 0.78230321,  0.78230321,  0.78230321,  0.78230321],
        [ 0.63880349,  0.63880349,  0.63880349,  0.63880349],
        [-0.58852368, -0.58852368, -0.58852368, -0.58852368]],

       [[-1.5399924 , -1.5399924 , -1.5399924 , -1.5399924 ],
        [-0.52637526, -0.52637526, -0.52637526, -0.52637526],
        [ 0.76043897,  0.76043897,  0.76043897,  0.76043897],
        [ 0.83754503,  0.83754503,  0.83754503,  0.83754503],
        [ 0.97572897,  0.97572897,  0.97572897,  0.97572897]],

       [[-0.02177147, -0.02177147, -0.02177147, -0.02177147],
        [ 2.00209365,  2.00209365,  2.00209365,  2.00209365],
        [ 1.86983552,  1.86983552,  1.86983552,  1.86983552],
        [ 0.06865877,  0.06865877,  0.06865877,  0.06865877],
        [ 0.48804842,  0.48804842,  0.48804842,  0.48804842]],

       [[ 0.15469091,  0.15469091,  0.15469091,  0.15469091],
  

In [87]:
t = hs * ar
t

array([[[-7.21970387e-01, -1.02595096e-01,  2.98322716e-02,
          4.06254418e-01],
        [ 2.72063579e+00,  1.59338702e+00, -1.48460254e-01,
          2.51490935e+00],
        [-1.62649570e-01, -9.27251822e-02, -1.55794032e+00,
          5.13408186e-01],
        [ 2.09915887e-01,  5.27413331e-01, -2.01020792e-01,
         -3.28608999e-01],
        [ 5.79029789e-01,  4.52641758e-02,  9.37455164e-01,
          1.21548257e-01]],

       [[-3.00189539e+00, -8.81699279e-01, -2.52791686e+00,
         -2.91200103e+00],
        [-2.50687606e-01, -8.81695819e-01,  4.38792398e-03,
         -3.31336640e-02],
        [ 1.23966687e-01, -1.53133470e+00, -9.58523536e-01,
         -1.58917865e+00],
        [ 1.37708124e+00,  1.07409389e+00, -7.80966825e-01,
         -9.32588392e-01],
        [-5.63053921e-01,  6.74863794e-01,  1.35868086e+00,
         -3.82307604e-01]],

       [[-1.13637967e-02, -3.30830362e-02,  1.43920567e-02,
         -1.70308786e-02],
        [-2.73664826e+00, -1.57725062e+

In [88]:
print(t.shape)

(10, 5, 4)


In [89]:
c = np.sum(t, axis=1)
c

array([[ 2.62496151,  1.97074425, -0.94013393,  3.22751121],
       [-2.31458899, -1.54577212, -2.90433844, -5.84920934],
       [-2.82344776, -3.21523307,  3.20006725, -4.98316375],
       [ 1.8459354 ,  2.80248848, -3.15198558,  0.64192403],
       [-0.34971195, -1.41374706,  0.10003548, -0.16413278],
       [-2.57039303, -0.12781054, -0.01928305, -3.08315027],
       [-1.16901618, -0.31494258, -0.57361104,  0.62077587],
       [-1.02356695, -0.55549574, -1.814649  , -1.32597403],
       [ 0.15565844,  6.16969887, -0.9270854 ,  1.90404559],
       [ 0.41610085,  2.14471397,  1.95778409,  3.18057325]])

In [90]:
print(c.shape)

(10, 4)


In [91]:
import sys
sys.path.append('..')
import tensorflow as tf
import numpy as np

In [92]:
N, T, H = 10, 5, 4
hs = np.random.randn(N, T, H)
hs

array([[[-1.44220327e+00, -6.12345158e-01, -1.58344218e+00,
          1.42524784e+00],
        [-8.42662161e-01,  3.52407060e-01, -1.06947078e-02,
          4.44112817e-01],
        [-1.17157994e+00, -2.49877151e-01,  2.90434654e-01,
          1.13925372e+00],
        [-1.75762163e+00,  2.56910489e-01, -1.15001545e+00,
         -6.63785548e-01],
        [-1.21520139e-01, -1.62900432e-01, -4.57847835e-01,
         -1.43262762e-01]],

       [[-4.01753250e-01,  1.14610977e+00,  1.14680852e+00,
          7.72305866e-01],
        [ 6.35933306e-01,  1.00266006e+00,  2.67443329e-01,
         -5.46703401e-01],
        [-1.57980212e+00,  7.77195215e-01,  5.74857446e-01,
          1.54032704e-01],
        [-2.47402063e+00, -1.23323448e+00, -1.73201746e-02,
         -1.17724926e+00],
        [-2.26929215e-01, -1.21532187e-01,  7.29794800e-01,
         -1.12329082e+00]],

       [[-1.98896981e+00, -4.64426409e-01, -1.07179245e+00,
         -5.98911835e-02],
        [ 3.06483165e-01, -1.89942131e-

In [93]:
h = np.random.randn(N, H)
h

array([[ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ],
       [ 1.68213299, -0.35459267,  0.81309514,  1.24932229],
       [-0.63946687,  1.0225643 , -0.23084219,  0.45504707],
       [-0.01887838, -0.5178614 , -0.39619788,  0.21876074],
       [-1.39601985,  2.33509248,  1.32628493,  0.06715865],
       [-1.03147323, -0.9683773 ,  0.31103523,  0.55291958],
       [-0.36020488,  2.30604007,  0.59973967,  1.21695702],
       [-1.48770573, -0.50632152, -0.19749171, -0.63878253],
       [ 0.88364264,  3.0109124 , -1.40183352, -0.85677985],
       [-0.76392582, -0.06304353, -1.29765771,  0.40283464]])

In [94]:
hr = h.reshape(N, 1, H).repeat(T, axis=1)
hr

array([[[ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ],
        [ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ],
        [ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ],
        [ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ],
        [ 0.59494743,  0.54265226,  1.51740987, -0.0597831 ]],

       [[ 1.68213299, -0.35459267,  0.81309514,  1.24932229],
        [ 1.68213299, -0.35459267,  0.81309514,  1.24932229],
        [ 1.68213299, -0.35459267,  0.81309514,  1.24932229],
        [ 1.68213299, -0.35459267,  0.81309514,  1.24932229],
        [ 1.68213299, -0.35459267,  0.81309514,  1.24932229]],

       [[-0.63946687,  1.0225643 , -0.23084219,  0.45504707],
        [-0.63946687,  1.0225643 , -0.23084219,  0.45504707],
        [-0.63946687,  1.0225643 , -0.23084219,  0.45504707],
        [-0.63946687,  1.0225643 , -0.23084219,  0.45504707],
        [-0.63946687,  1.0225643 , -0.23084219,  0.45504707]],

       [[-0.01887838, -0.5178614 , -0.39619788,  0.21876074],
  

In [95]:
t = hs * hr
t

array([[[-8.58035135e-01, -3.32290484e-01, -2.40273079e+00,
         -8.52057374e-02],
        [-5.01339689e-01,  1.91234488e-01, -1.62282551e-02,
         -2.65504419e-02],
        [-6.97028480e-01, -1.35596401e-01,  4.40708411e-01,
         -6.81081216e-02],
        [-1.04569247e+00,  1.39413057e-01, -1.74504480e+00,
          3.96831592e-02],
        [-7.22980945e-02, -8.83982875e-02, -6.94742824e-01,
          8.56469233e-03]],

       [[-6.75802396e-01, -4.06402123e-01,  9.32464433e-01,
          9.64858930e-01],
        [ 1.06972439e+00, -3.55535907e-01,  2.17456871e-01,
         -6.83008743e-01],
        [-2.65743726e+00, -2.75587725e-01,  4.67413795e-01,
          1.92436490e-01],
        [-4.16163172e+00,  4.37295906e-01, -1.40829498e-02,
         -1.47076373e+00],
        [-3.81725120e-01,  4.30944225e-02,  5.93392604e-01,
         -1.40335226e+00]],

       [[ 1.27188031e+00, -4.74905863e-01,  2.47414917e-01,
         -2.72533074e-02],
        [-1.95985832e-01, -1.94228041e-

In [96]:
s = np.sum(t, axis=2)
s

array([[-3.67826215, -0.3528839 , -0.46002459, -2.61164105, -0.84687451],
       [ 0.81511884,  0.24863662, -2.2731747 , -5.2091825 , -1.14859035],
       [ 1.01713605, -0.04211308, -0.94950612,  0.53523266,  1.67538152],
       [-0.16237451, -0.36485129, -0.85167392, -0.52759537,  0.07291926],
       [-5.61786588, -1.69075291,  2.48089927, -1.81813421, -3.31978323],
       [ 0.62699032, -0.16371407,  0.61071457, -0.98083587,  0.51314461],
       [ 2.29591917, -2.45706462,  2.00424725, -4.86489882, -3.28145897],
       [-0.3863328 ,  1.3192668 , -0.37216897, -0.10433595,  0.75552695],
       [ 0.17804801,  0.17222607, -0.37038086,  5.556548  ,  0.17949375],
       [ 0.808991  , -1.02645463,  1.09140885, -0.21580745, -0.0325906 ]])

In [100]:
sess = tf.Session()
soft = sess.run(tf.nn.softmax(s))
print(soft)

[[1.35743964e-02 3.77497389e-01 3.39143377e-01 3.94410241e-02
  2.30343814e-01]
 [5.69523383e-01 3.23214960e-01 2.59586866e-02 1.37781444e-03
  7.99251560e-02]
 [2.47791599e-01 8.59133240e-02 3.46724662e-02 1.53037757e-01
  4.78584854e-01]
 [2.33756451e-01 1.90910167e-01 1.17328813e-01 1.62237110e-01
  2.95767458e-01]
 [2.94394128e-04 1.49435106e-02 9.68675144e-01 1.31562356e-02
  2.93071615e-03]
 [2.83278139e-01 1.28473781e-01 2.78704892e-01 5.67470143e-02
  2.52796173e-01]
 [5.68117780e-01 4.90053786e-03 4.24391696e-01 4.41097548e-04
  2.14888825e-03]
 [8.34911786e-02 4.59592663e-01 8.46821483e-02 1.10690480e-01
  2.61543531e-01]
 [4.53987294e-03 4.51351883e-03 2.62339728e-03 9.83776770e-01
  4.54644112e-03]
 [3.05271528e-01 4.87037488e-02 4.04891642e-01 1.09552423e-01
  1.31580658e-01]]
